-- The synthesis layer for AI-assisted documents: document-level metadata,
-- section-level verification status, and versioning.
--
-- The layer itself already exists. text_type = 'synthesis' is in the locked
-- vocabulary (rag_corpus_text_type_check) and carries 117 live rows from the
-- Synthesis agent ('Arete Synthesis'). This migration adds no layer column
-- and no text_type value: text_type is the one fence field, and a second
-- field alongside it could disagree with it
-- (docs/corpus/PUBLIC_DOMAIN_INGESTION_PROPOSAL.md §2). How the spec's fields
-- land:
--
--   layer            rag_corpus.text_type = 'synthesis' (existing)
--   source_type      rag_corpus.source_type = 'synthesis' (existing column)
--   author           rag_corpus.author and the document row: 'Arete (AI-assisted)'
--   title            rag_corpus.work and the document row
--   version, created_at, generated_with, reviewed_by, sources_used,
--   regenerate_when, active
--                    corpus_synthesis_documents (new, one row per version)
--   section heading  rag_corpus.section_label (existing)
--   verification_status
--                    rag_corpus.verification_status (new, text[]: a section
--                    can be both interpretive and unverified)
--   active = false   the version's chunks are deprecated = true, which every
--                    match_rag_corpus* function already filters on
--
-- Writes nothing to existing rows. The synthesis documents themselves are
-- loaded by the next migration, generated by
-- academy/corpus-ingestion/ingest-synthesis.js --emit-sql.

begin;

-- ---------------------------------------------------------------------------
-- Document versions
-- ---------------------------------------------------------------------------
create table if not exists public.corpus_synthesis_documents (
  id               uuid primary key default gen_random_uuid(),
  doc_key          text not null check (doc_key ~ '^[a-z0-9-]+$'),
  version          integer not null check (version >= 1),
  title            text not null,
  author           text not null default 'Arete (AI-assisted)',
  created_at       date not null,                 -- the date the document was written
  generated_with   text not null,                 -- model and surface
  reviewed_by      text,                          -- 'Kyle' once he has signed off
  sources_used     text[] not null default '{}',  -- 'Author | Work', as rag_corpus names them
  regenerate_when  text[] not null default '{}',  -- works whose arrival should prompt a rewrite
  active           boolean not null default false,
  file_path        text not null,                 -- the committed Markdown this version was loaded from
  content_sha256   text not null,                 -- of that file; a changed file is a new version
  loaded_at        timestamptz not null default now(),
  unique (doc_key, version)
);

create unique index if not exists corpus_synthesis_documents_one_active
  on public.corpus_synthesis_documents (doc_key) where active;

comment on table public.corpus_synthesis_documents is
  'AI-assisted synthesis documents in rag_corpus, one row per version. Chunks point here through rag_corpus.synthesis_document_id. Only the active version''s chunks are live; set it with activate_synthesis_version(). Distinct from synthesis_documents, the Synthesis agent''s review queue.';

alter table public.corpus_synthesis_documents enable row level security;
revoke all on public.corpus_synthesis_documents from anon, authenticated;

-- ---------------------------------------------------------------------------
-- rag_corpus: section status and the document link
-- ---------------------------------------------------------------------------
alter table public.rag_corpus
  add column if not exists verification_status   text[],
  add column if not exists synthesis_document_id uuid references public.corpus_synthesis_documents (id);

comment on column public.rag_corpus.verification_status is
  'Synthesis chunks only. corpus_verified: written from and checked against corpus passages. via_summary: checked against the corpus, but the corpus source is itself a summary of a book or paper. unverified: from general knowledge, not checked against a corpus text. interpretive: application or guidance, not a report of what sources say. The chunk_text header repeats it for the model.';
comment on column public.rag_corpus.synthesis_document_id is
  'The corpus_synthesis_documents version this chunk belongs to. Null for every other row, including the Synthesis agent''s own documents.';

alter table public.rag_corpus
  add constraint rag_corpus_verification_status_check check (
    verification_status is null
    or (text_type = 'synthesis'
        and cardinality(verification_status) >= 1
        and verification_status <@ array['corpus_verified', 'via_summary', 'unverified', 'interpretive']::text[])
  ) not valid;
alter table public.rag_corpus validate constraint rag_corpus_verification_status_check;

alter table public.rag_corpus
  add constraint rag_corpus_synthesis_document_check check (
    synthesis_document_id is null
    or (text_type = 'synthesis' and verification_status is not null)
  ) not valid;
alter table public.rag_corpus validate constraint rag_corpus_synthesis_document_check;

create index if not exists rag_corpus_synthesis_document_idx
  on public.rag_corpus (synthesis_document_id) where synthesis_document_id is not null;

-- ---------------------------------------------------------------------------
-- Versioning: one call makes a version active and retires the others
-- ---------------------------------------------------------------------------
create or replace function public.activate_synthesis_version(p_document_id uuid)
returns void
language plpgsql
set search_path = public
as $$
declare
  v_key text;
begin
  select doc_key into v_key from corpus_synthesis_documents where id = p_document_id for update;
  if v_key is null then
    raise exception 'no synthesis document version %', p_document_id;
  end if;

  -- Deprecate, never delete: the old versions stay for history.
  update corpus_synthesis_documents set active = false
    where doc_key = v_key and id <> p_document_id and active;
  update rag_corpus r set deprecated = true
    from corpus_synthesis_documents d
    where r.synthesis_document_id = d.id and d.doc_key = v_key and d.id <> p_document_id
      and not r.deprecated;

  update corpus_synthesis_documents set active = true where id = p_document_id;
  update rag_corpus set deprecated = false
    where synthesis_document_id = p_document_id and deprecated;
end;
$$;

revoke all on function public.activate_synthesis_version(uuid) from public, anon, authenticated;
grant execute on function public.activate_synthesis_version(uuid) to service_role;

commit;
