-- Loads The Virtues of Socrates in Plato and Xenophon, version 1 (66 chunks), part 1 of 3,
-- into the synthesis layer defined in 20260929133029_synthesis_layer_documents.sql.
-- See academy/corpus-ingestion/synthesis/README.md.
--
-- Generated by: node academy/corpus-ingestion/ingest-synthesis.js --emit-sql --file virtues-of-socrates.v1.md --part 1/3
-- from the committed Markdown; the body is its output, unedited. Rows are written
-- without embeddings. The corpus agent's nightly synthesis sync (or the same script
-- run with keys) embeds live chunks that lack one; until then no match_rag_corpus*
-- function can return them, since each requires embedding is not null.
--
-- Touches no existing row. Every insert is on conflict do nothing.

begin;
-- The Virtues of Socrates in Plato and Xenophon, version 1: 66 chunks; part 1 of 3, chunks 1001 to 1022
insert into public.corpus_synthesis_documents
  (doc_key, version, title, author, created_at, generated_with, reviewed_by, sources_used, regenerate_when, file_path, content_sha256)
values ($q$virtues-of-socrates$q$, 1, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Arete (AI-assisted)$q$, $q$2026-09-29$q$::date, $q$Claude, Claude Docs (claude.ai)$q$, null, array[$q$Plato | Apology$q$, $q$Plato | Gorgias$q$, $q$Xenophon | Memorabilia$q$, $q$Seneca | Letters$q$, $q$Seneca | On Providence$q$, $q$Seneca | On Anger$q$, $q$Seneca | On Leisure$q$, $q$Seneca | On Benefits$q$, $q$Seneca | On Peace of Mind$q$, $q$Seneca | On the Shortness of Life$q$, $q$Epictetus | Discourses$q$, $q$Epictetus | Enchiridion$q$, $q$Marcus Aurelius | Meditations$q$, $q$Musonius Rufus | Lectures$q$, $q$Diogenes Laërtius | Lives of Eminent Philosophers$q$]::text[], array[$q$Plato, Symposium$q$, $q$Plato, Crito$q$, $q$Plato, Phaedo$q$, $q$Plato, Laches$q$, $q$Xenophon, Apology$q$, $q$Xenophon, Symposium$q$]::text[], $q$academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, $q$0ea0193d5389c2a5a9ec7412b2c9f85c0ba089641ad80d64095b21d1b4962501$q$)
on conflict (doc_key, version) do nothing;
insert into public.rag_corpus (program_id, author, work, section_label, chunk_index, chunk_text, word_count, translator, source_url, edition_year, text_type, source_type, language, difficulty, verification_status, deprecated, synthesis_document_id)
select v.*, sd.id from (values
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Introduction$q$, 1001, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Introduction.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Socrates wrote nothing, so his character comes down to us through two students who knew him: Plato and Xenophon. The Stoics took him as their model of the wise man, and Epictetus held him up again and again as proof that a human being can live by virtue alone.

This list gathers the moments in their writings that show Socrates practicing the four cardinal virtues. It draws on the works in the Arete corpus: Plato's Apology and Gorgias (Jowett's translation) and Xenophon's Memorabilia (Dakyns's translation). References to Plato use the standard page numbers, like Apology 28e; references to Xenophon give book, chapter, and section, like Memorabilia I.2.1. Several of the most famous episodes come from dialogues not yet in the corpus, and they are listed separately at the end.

Xenophon closes his book with his own summary of the man: so just that he never harmed anyone, so self-controlled that he never chose the pleasant over the better, and so wise that he never misjudged better from worse (Memorabilia IV.8.11).$q$, 170, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Courage$q$, 1002, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Courage.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- He held his post in battle. Socrates served as a soldier at Potidaea, Amphipolis, and Delium and stayed where his commanders stationed him, facing death. He argued he must hold his post in philosophy just as firmly, where the god had placed him (Apology 28e).

- He refused to stop philosophizing, even to save his life. Offered release on condition that he stop questioning people, he said he would obey the god rather than the Athenians and would not change his ways even if he had to die many times (Apology 29c to 30c).

- He stood alone against the Assembly at the trial of the generals. When the Athenians wanted to try the generals of Arginusae together, which was illegal, Socrates was the only presiding officer to oppose it, though the orators threatened to impeach and arrest him (Apology 32b; Memorabilia I.1.18, IV.4.2).

- He defied the Thirty Tyrants over Leon of Salamis. Ordered with four others to bring in Leon to be executed, Socrates simply went home, knowing it might cost him his life (Apology 32c to 32d; Memorabilia IV.4.3).

- He mocked the Thirty to their faces. While they were killing citizens, he remarked that a herdsman who kept shrinking his herd would be called a poor herdsman, and so should a ruler who kept shrinking the city (Memorabilia I.2.32).

- He questioned Critias and Charicles when they tried to silence him. Summoned and forbidden to talk with young men, he calmly asked them to define their terms, until Charicles lost his temper (Memorabilia I.2.33 to 38).

- He would not beg for his life. He refused to weep before the jury or parade his children, saying it would disgrace him and the city and ask the judges to break their oath (Apology 34c to 35d). Xenophon adds that he could easily have been acquitted by a little flattery, and chose to obey the law and die (Memorabilia IV.4.4).

- He proposed a reward instead of a penalty. Asked to propose his own punishment, he said a public benefactor deserved free meals in the Prytaneum, the honor given to Olympic victors (Apology 36d to 37a).

- He refused to fear death. To fear death is to think you know what you do not; no one knows whether it is the greatest good. He knew only that doing wrong and disobeying a better is evil (Apology 29a to 29b).

- He met his sentence without bitterness. He told the jury no evil can happen to a good man in life or in death (Apology 41c to 41d). Xenophon reports he bore his last days with a cheerfulness that astonished his friends (Memorabilia IV.8.2).$q$, 436, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Courage > Modern examples to strive for$q$, 1003, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Courage > Modern examples to strive for.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Be the one who says no in the room. When a meeting drifts toward something unfair or dishonest, say so plainly, even if you are the only one, as Socrates was at the trial of the generals.

- Refuse the unethical order quietly. If a boss or client asks you to falsify a report, mislead a customer, or cut a corner that could hurt someone, decline and go home, the way Socrates did with Leon of Salamis. You do not need a speech.

- Stay at your post when it gets hard. Keep showing up for the difficult obligation: the aging parent, the struggling marriage, the project everyone else has abandoned.

- Tell the truth to people with power over you. Give an honest assessment to a manager, a board, or a client who would rather hear something else.

- Do not beg for approval. In a performance review, a conflict, or an online argument, make your case honestly and let it stand without flattery or self-abasement.

- Face the diagnosis, the layoff, or the loss without pretending to know it is the worst thing. Take the next right step and leave the rest open, as Socrates did about death.

- Keep your practice when it costs you. Whatever your version of philosophy is, whether honesty, faith, or principle, do not drop it just because it has become inconvenient or unpopular.$q$, 225, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Self-discipline and temperance$q$, 1004, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Self-discipline and temperance.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- He mastered his appetites and endured hardship. Xenophon calls him the most self-controlled of men in matters of sex and food, able to endure winter cold and summer heat and every kind of toil, and trained to need so little that he always had enough (Memorabilia I.2.1).

- He lived on almost nothing. Antiphon the sophist mocked him for eating poor food, wearing one cloak winter and summer, and going barefoot. Socrates answered that hunger is the best sauce, that he trained his body to bear whatever came, and that the greatest pleasure is knowing you are becoming better and making better friends (Memorabilia I.6.2 to 10).

- He ate and drank only for need. He ate only as much as he could eat with pleasure and came to meals hungry enough that appetite was his seasoning (Memorabilia I.3.5 to 6).

- He took no money for his company. He called those who charged for their conversation sellers of themselves, and valued his freedom to talk with whomever he chose (Memorabilia I.2.5 to 7, I.6.5).

- He warned against the pull of beauty. When Critobulus kissed a handsome youth, Socrates told Xenophon that a kiss is more dangerous than a tarantula's bite and advised him to run from such beauty without looking back. For himself, Xenophon says, he was so well armed that abstaining from the most beautiful was easier for him than for others to abstain from the plainest (Memorabilia I.3.8 to 15).

- He rebuked Critias in public. When Critias, later the most violent of the Thirty, kept pursuing young Euthydemus, Socrates told him it was unworthy of a free man, and when that failed, mocked his desire before the company. Critias never forgave him (Memorabilia I.2.29 to 31).

- He taught self-control as the foundation of virtue. He asked what man could learn or practice anything good without self-control, and called the self-controlled man free and the slave to pleasure the least free of all (Memorabilia I.5, IV.5).

- He poked fun at gluttony. At shared dinners he teased the man who ate his relish without bread, and warned that mixing many dainties in one mouthful spoils them all (Memorabilia III.14).

- He never chose the pleasant over the better. Xenophon's final judgment: in all his life he never preferred what was sweeter to what was better (Memorabilia IV.8.11).$q$, 384, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Self-discipline and temperance > Modern examples to strive for$q$, 1005, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Self-discipline and temperance > Modern examples to strive for.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Put the phone down. Treat the endless scroll the way Socrates treated the tempting kiss: the pull is stronger than it looks, so keep your distance rather than trusting yourself to resist up close.

- Eat when hungry and stop when satisfied. Let appetite be the seasoning, and skip the snacking, the second helping, and the drink you do not really want.

- Train for discomfort on purpose. Take the cold shower, the hard workout, the long walk in bad weather, so that hardship does not rule you when it comes uninvited.

- Want less. Wear the same few clothes, keep the old car running, and measure wealth by how little you need, as Socrates answered Antiphon.

- Do not sell your time or judgment to the highest bidder. Turn down the job, client, or sponsorship that would make you say what you do not believe.

- Choose the better over the sweeter. Pick the book over the show, the early morning over the late night, and the hard conversation over the easy avoidance.

- Hold friends to a standard, kindly. When a friend is pursuing something that will hurt them or someone else, say so, as Socrates did with Critias, even if it costs you the friendship.$q$, 202, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Wisdom$q$, 1006, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Wisdom.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- He knew that he did not know. When the oracle at Delphi told Chaerephon that no one was wiser than Socrates, he set out to prove it wrong. He questioned politicians, poets, and craftsmen and found that each thought he knew things he did not. He concluded that his only wisdom was knowing the limits of his knowledge, and that the god meant human wisdom is worth little or nothing (Apology 21a to 23b).

- He kept examining, whatever it cost him. He called this questioning his service to the god, and it earned him enemies and poverty, but he would not give it up (Apology 22e to 23c).

- He held the unexamined life not worth living. Rather than go quietly into exile, he told the jury that daily talk about virtue is the greatest good for a man, and that life without such examination is not worth living (Apology 38a).

- He called himself the city's gadfly. He compared himself to a gadfly sent by the god to wake a great but sluggish horse, reminding each citizen to care for his soul before his wealth (Apology 30a to 30e).

- He humbled a would-be statesman. Young Glaucon, not yet twenty, was eager to lead Athens. Socrates gently asked him about the city's revenues, expenses, army, silver mines, and grain supply, until Glaucon saw he knew none of it and should learn before he led (Memorabilia III.6).

- He urged a capable man into public life. Charmides was able but afraid to speak before the Assembly. Socrates showed him he already outargued its leaders in private, and told him not to be ignorant of himself (Memorabilia III.7).

- He brought a proud reader to know himself. Euthydemus had collected the books of poets and philosophers and thought himself wise. Through questions about justice, Socrates led him to see he could not define what he thought he knew, and pointed him to the Delphic command to know yourself (Memorabilia IV.2).

- He held that virtue is knowledge. He did not separate wisdom from self-control, and said justice and every other virtue is wisdom, since all fine actions are done by those who know (Memorabilia III.9.4 to 5).

- He fitted his teaching to each person. He tamed those proud of their natural gifts by showing that the best natures most need training, and treated the rich, the shy, and the arrogant differently (Memorabilia IV.1).

- He limited study to what is useful. He encouraged enough geometry to measure land and enough astronomy to tell the seasons, but warned against studies that consume a life and yield nothing for living well (Memorabilia IV.7).$q$, 433, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Wisdom > Modern examples to strive for$q$, 1007, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Wisdom > Modern examples to strive for.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Say "I don't know" out loud. In a meeting, with your kids, or with a client, admit the limits of your knowledge instead of bluffing. It is the beginning of Socratic wisdom.

- Check your own confidence. Before you post, argue, or decide, ask the questions Socrates asked Glaucon: do I actually know the numbers, the history, the facts behind my opinion?

- Examine your day. Keep a journal or an evening review asking what you did well, where you fell short, and what you will do differently, so that your life is examined and not just lived.

- Ask questions instead of lecturing. When someone you are mentoring is headed the wrong way, ask them to walk you through their reasoning, the way Socrates led Euthydemus to see for himself.

- Encourage the capable but timid. Notice the colleague or student who knows more than they let on, and push them forward, as Socrates did with Charmides.

- Learn what is useful for living well. Spend your study time on what makes you a better person, parent, and citizen, not on trivia or endless information you will never use.

- Be the gadfly your community needs. Kindly and persistently remind the people around you of what matters more than money and status.$q$, 207, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Justice: how he treated people$q$, 1008, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Justice: how he treated people.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- He never wronged anyone. Near death he said he knew he would be remembered as one who never wronged any man or made anyone worse, but always tried to make his companions better (Memorabilia IV.8.10).

- He showed justice by deeds, not definitions. When the sophist Hippias demanded his definition of justice, Socrates answered that he showed it in what he did, and asked whether Hippias had ever seen him bear false witness, inform on anyone, or stir up quarrels among friends or strife in the city. Hippias admitted he had not (Memorabilia IV.4.10 to 11).

- He would rather suffer wrong than do it. Against Polus and Callicles he argued that doing injustice is worse than suffering it, and escaping punishment worst of all (Gorgias 469b to 469c, 474b to 479e).

- He kept the law even when it killed him. He obeyed the laws in private life and in office, refused unlawful orders from the Assembly and the Thirty, and at his trial would do nothing outside the law, preferring to die lawfully than live by breaking it (Memorabilia IV.4.1 to 4).

- He taught for free and stayed poor. He never took a fee from anyone, rich or poor, and his poverty was his witness that he spent his life on the city's good (Apology 31b to 31c, 33a to 33b; Memorabilia I.2.5 to 7).

- He helped a friend feed a household of fourteen. When civil war left Aristarchus with fourteen sisters, nieces, and cousins to support and no income, Socrates advised him to let them work at the skills they had. The women became productive and happy, and the household grew fond of him again (Memorabilia II.7).

- He found honest work for a friend fallen on hard times. He advised Eutherus, who had lost his property abroad and was living by manual labor, to find steady work as a steward before his strength gave out (Memorabilia II.8).

- He protected Crito from blackmailers. He suggested Crito take on Archedemus, an honest but poor speaker, to defend him from informers, and Archedemus became a loyal friend (Memorabilia II.9).

- He urged friends to help each other. He persuaded Diodorus that helping their struggling friend Hermogenes was worth more than saving a runaway slave (Memorabilia II.10).

- He taught a son to honor his mother. When his own son Lamprocles complained of his mother's harsh temper, Socrates showed him how much she had done for him and that no one would trust a man ungrateful to his parents (Memorabilia II.2).

- He reconciled two quarreling brothers. He told Chaerecrates to make the first kind move toward his brother Chaerephon, just as the hands and feet were made to help each other (Memorabilia II.3).$q$, 447, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Justice: how he treated people$q$, 1009, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Justice: how he treated people.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- He asked people to weigh their worth as friends. He urged his companions to ask what they were worth to their friends, and taught that good friends are the most valuable possession (Memorabilia II.4 to 6).

- He checked anger at a slave. When a man beat his servant as lazy and greedy, Socrates asked whether he had ever considered which of the two deserved the beating more (Memorabilia III.13.4).

- He forgave his judges. He told them he was not angry with those who condemned him, and asked only that they correct his sons as he had corrected them if they cared for money before virtue (Apology 41d to 42a).$q$, 109, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Justice: how he treated people > Modern examples to strive for$q$, 1010, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Justice: how he treated people > Modern examples to strive for.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Let your record speak. Aim to be someone about whom no one can say you lied about them, spread gossip, or set friends against each other, the test Socrates put to Hippias.

- Take the loss rather than cheat. Accept losing the deal, the argument, or the promotion before winning it by deceit or cruelty.

- Help a friend solve the real problem. When someone is struggling with money, work, or family, think with them about practical steps, as Socrates did for Aristarchus and Eutherus, not just offer sympathy.

- Make the introduction. Connect the person who needs help with the person who can give it, the way Socrates brought Crito and Archedemus together.

- Honor your parents, even the difficult ones. Remember what they gave you before you list what they got wrong, as Socrates taught Lamprocles.

- Make the first move toward reconciliation. Call the sibling, old friend, or colleague you have fallen out with. Do not wait for them to go first.

- Watch how you treat those under you. Before you lose your temper with an employee, a waiter, or your kids, ask whether you are the one who needs correcting.

- Give your knowledge freely. Mentor, teach, and share what you know with people who cannot pay you back.

- Forgive the people who wronged you. Let go of resentment toward those who have harmed you, and still ask the people around you to hold your children to a high standard.$q$, 238, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms$q$, 1011, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Neither Socrates nor the Stoics made rules for every activity. They gave a way of judging, and then applied it to whatever life brought. This section runs the ordinary activities of modern life through that judgment. The verdicts are Practice (build it into your life), In moderation (fine within limits, dangerous past them), and Avoid (it works against virtue by its nature).$q$, 62, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Six tests$q$, 1012, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Six tests.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Every verdict below comes from one or more of these questions.

1. Better or sweeter? Does this make me better, or only feel good? Socrates never chose the sweeter over the better (Memorabilia IV.8.11).

2. Master or slave? Can I take it or leave it, or does it pull me? The Stoics called the person ruled by pleasure the least free of all (Memorabilia IV.5).

3. Does it keep my judgment clear? Reason is the one thing wholly ours. Whatever clouds it gives away the self (Epictetus; Seneca, Letters 83).

4. Is it up to me? Put effort into what I control, my choices, and not into what I don't, like others' opinions or the news (Epictetus, Handbook 1).

5. How does it treat people? Justice asks whether an activity uses, harms, or neglects someone.

6. Would I do it with someone I respect watching? Seneca advised imagining Cato looking on (Letters 11). Pick your own: Socrates, your wife, your children.$q$, 161, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > The body$q$, 1013, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > The body.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Food|In moderation|Eat when hungry and stop when satisfied; plain food, with hunger as the sauce (Memorabilia I.3.5 to 6, I.6.5)|Grazing all day, eating from boredom or stress, living for the next meal|
|Alcohol|In moderation|A drink with friends or a meal, never past clear judgment; Socrates drank but was never drunk|Getting drunk, which Seneca called voluntary madness (Letters 83); drinking to cope; keeping it in reach every night|
|Recreational drugs|Avoid|A mind you never hand over to a substance; medicine taken as prescribed is a different matter|Using anything to get high, escape, or numb; it fails the third test by design|
|Coffee and caffeine|In moderation|A cup that serves your work; now and then go without, to prove it doesn't own you, as Seneca practiced going without comforts (Letters 18)|Not being able to function or be civil without it; caffeine to override the sleep you owe your body|
|Exercise|Practice|Train regularly for strength and endurance so hardship finds you ready; Socrates urged young men to stay fit (Memorabilia III.12) and trained himself against cold and toil|Neglecting the body, or the reverse: making fitness a vanity, an obsession, or a performance for others; Seneca advised short, simple exercise that leaves time for the mind (Letters 15)|
|Sleep|Practice|Enough sleep to keep your judgment sharp; get up when it's time, since you were made to act, not lie in bed (Meditations V.1)|Staying up scrolling; sleeping late as a habit; treating rest as a reward instead of a duty|
|Sex|Within marriage|Faithfulness and self-control; Epictetus advised restraint and warned against both indulgence and preaching at others (Handbook 33)|Treating people as objects; infidelity; letting desire decide for you, which Socrates compared to a tarantula's bite (Memorabilia I.3.12)|
|Pornography|Avoid|Keep your distance, as Socrates told Xenophon to run from beauty without looking back (Memorabilia I.3.13)|Watching it at all; it enslaves by habit, trains you to use people, and works on impressions you never examine|
|Cold, discomfort, and hardship|Practice|Seek some voluntarily: the cold shower, the fast, the long walk in bad weather, so that hardship doesn't rule you when it comes uninvited|Arranging life so you are never uncomfortable, then collapsing when you are|$q$, 355, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Diet$q$, 1014, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Diet.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Socrates gave the rule that settles most of modern eating: avoid any food that tempts you to eat when you are not hungry, and any drink that tempts you to drink when you are not thirsty (Memorabilia I.3.6). Musonius Rufus, who wrote more on food than any other Stoic, called eating the hardest pleasure to fight, because it tempts us every day and usually twice a day. He favored cheap, plentiful food, eaten for nourishment rather than pleasure (Lectures XVIIIA and XVIIIB). Epictetus added that spending much time on eating is a sign of a dull mind, since the body should be tended in passing (Handbook 41). Eating animals is treated separately below as an open question.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Plain, whole food|Practice|Simple meals of grains, vegetables, cheese, and honey, as Musonius advised, with hunger as the sauce|Making every meal an event; needing flavor and variety to eat at all|
|Ultra-processed and snack food|Avoid|Food that stops being appealing once you are full|Food engineered to make you eat past hunger, exactly what Socrates warned against|
|Set meals|Practice|Eat at meals, on purpose, then stop|Grazing through the day; the kitchen as a place you drift to|
|Eating in front of a screen|Avoid|Eat at a table, with others when you can, paying attention to the food|Eating without tasting or noticing when you have had enough|
|Sugar and dessert|Avoid as a habit|An occasional sweet at a shared table|A nightly dessert you would miss; sweetness as a reward you think you have earned|
|Fasting|Practice, as training|Days of going without so that hunger never frightens you, as Seneca kept (Letters 18)|Fasting for appearance or pride; making it a performance|
|Fine dining and feasts|In moderation|A good meal with friends, enjoyed and then forgotten|Spending money and attention chasing the next great meal; judging a day by what you ate|
|Diet obsession|Avoid|Eat simply and think about it little (Handbook 41)|Fads, tracking every bite, supplements as a hobby, food as identity; the same fault as gluttony, too much of the mind given to the stomach|$q$, 336, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Attention and screens$q$, 1015, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Attention and screens.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

The Stoics had no phones, but they knew the problem. Epictetus taught that the one thing wholly ours is how we use our impressions, and every screen is a machine for supplying impressions faster than we can examine them.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Social media|Only as a tool|Use it as a tool with a purpose: post the work, answer the message, close the app. Marcus noted how much time you gain by not looking to see what your neighbor said or did (Meditations IV.18)|Scrolling to fill every gap; posting for approval; measuring your worth in likes; comparing your life to other people's highlights|
|Online arguments|Avoid|Make your case once, honestly, and let it stand, as Socrates did with the jury|Arguing with strangers to win; outrage as entertainment; saying online what you would never say face to face|
|Television and streaming|Avoid as entertainment|Watch only what you choose deliberately because it teaches, then turn it off; Epictetus saw dramas as people suffering over externals|Watching by default, bingeing into the night, letting autoplay decide; Seneca warned that he came home from the crowds and shows more cruel and more greedy (Letters 7)|
|News|In moderation|Know enough to be a responsible citizen and neighbor, then act on what is up to you|Constant checking; anxiety and anger over things you cannot affect; letting the news cycle set your mood|
|The phone itself|In moderation|Keep it out of the bedroom, off the dinner table, and away during conversation|Reaching for it on reflex; checking it while someone is talking to you; the first and last thing you touch each day|
|Video games|Avoid, except as play with your children|Play that is really care for someone else|Hours lost alone; games designed to hook you with rewards and purchases|
|Reading|Practice|Read the wise of old, as Socrates did with his friends, unrolling their books together and taking what was good (Memorabilia I.6.14)|Reading only to seem learned, the "inn" Epictetus warned of (Discourses II.23); hoarding books unread, like Euthydemus|$q$, 325, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Money and work$q$, 1016, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Money and work.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Work|Practice|Do your role well, whatever it is; Epictetus taught that each role, parent, citizen, worker, carries its own duties|Coasting; doing the minimum; or the reverse, letting work swallow family, health, and thought|
|Earning money|In moderation|Earn honestly and enough; the Stoics counted wealth as a preferred thing, never a good in itself|Chasing money for its own sake; letting income decide what you believe or say|
|Spending|In moderation|Buy what serves a real need; want less, as Socrates did|Shopping for comfort or status; buying things to impress people you don't know|
|Debt|Avoid where possible|Live within your means so you stay free|Borrowing for pleasures and appearances; the Stoics prized freedom, and debt sells it|
|Gambling|Avoid|Take your risks on work and people, where effort matters|Betting for the thrill or to get rich; it hands your outcome to chance and trains the itch|
|Giving and generosity|Practice|Help friends practically, as Socrates did for Aristarchus; share what you know without charge|Giving for credit or praise; lending to control people|
|Business dealings|Practice honesty|Tell the whole truth about what you sell; keep your word when it costs you|Misleading customers, fine print, or promises you know you won't keep; winning a deal by deceit, which Socrates held worse than losing it|$q$, 205, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Relationships and speech$q$, 1017, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Relationships and speech.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Marriage|Practice|Faithfulness, partnership, and care; the Stoic Musonius Rufus called marriage a full sharing of life|Treating your spouse as furniture; flirting elsewhere; keeping score|
|Parenting|Practice|Teach by example, as Socrates made his companions better by being good himself (Memorabilia I.2.3); correct your children when they value money over virtue (Apology 41e)|Parenting by screen; anger as discipline; wanting children to look successful more than to be good|
|Parents and family|Practice|Gratitude to your parents despite their faults, as Socrates taught Lamprocles; make the first move with estranged siblings|Holding grudges; listing their failures while forgetting what they gave you|
|Friendship|Practice|Few, good friends; ask what you're worth to them (Memorabilia II.5); help in practical ways|Friendships for use or status; disappearing when a friend is in trouble|
|Gossip|Avoid|Speak of people as if they were present; Epictetus advised above all not to talk about other people, praising, blaming, or comparing (Handbook 33)|Talking behind backs; sharing others' failures for entertainment|
|Anger|Avoid|No anger at all: the one who wrongs you errs unwillingly, so there is nothing to be angry at; ask, as Socrates asked the man beating his servant, which of you deserves correction|Venting on those beneath you: employees, waiters, children, anyone who can't answer back|
|Honesty|Practice|Say what's true, plainly, even when it costs you, as Socrates did with Critias and the jury|White lies for convenience; flattery; staying silent to avoid trouble|
|Conflict|Practice fairly|Question rather than attack; seek the truth together|Winning at the cost of truth; humiliating the other person|
|Forgiveness|Practice|Let go of resentment, as Socrates did with his judges|Nursing grudges; revenge, which Socrates rejected even for wrongs done to you|$q$, 266, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Public life$q$, 1018, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Public life.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Citizenship|Practice|Do your civic duties faithfully, as Socrates did as a soldier and as a presiding officer; obey the law, and refuse orders that are clearly unjust|Ignoring your community; or treating politics as a team sport where your side can do no wrong|
|Politics and public opinion|In moderation|Form views carefully, know the facts, as Socrates asked of Glaucon, and hold them with humility|Tribal anger; certainty without knowledge; letting opinions of the crowd decide yours, which Cleanthes told Stoics to ignore|
|Reputation|Not up to you|Be good and let reputation follow or not|Managing your image; doing good for credit; fearing what others think more than doing right|
|Status and ambition|In moderation|Seek responsibility when you can do it well, as Socrates urged Charmides|Chasing titles, followers, or prestige; ambition beyond your competence, as Glaucon's was|$q$, 135, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Habits, tools, and hard things$q$, 1019, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Habits, tools, and hard things.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|YouTube and online video|Only as a tool|Watch with a purpose, then stop; put up barriers, such as no app on the phone, so the choice is made before the pull begins|Rabbit holes, autoplay, and "one more"; the pull is designed to be stronger than your intention in the moment|
|Watching life through a phone|Avoid|Be present at the recital, the game, the parade; let the memory be yours|Recording instead of watching; your child looking up to see your phone instead of your face|
|AI tools|In moderation|Use AI to question, teach, and test you, as Socrates taught by asking; keep doing your own thinking and writing|Letting AI think, write, or decide for you; outsourcing the effort that forms judgment|
|Podcasts and audiobooks|In moderation|Learning on a drive or a run, followed up by reading the source itself|Constant background input so you are never alone with your thoughts|
|Streaks, trackers, and metrics|In moderation|Use the numbers as a tool for training; the progress that counts is in character|Chasing a perfect streak; letting an app or a score decide whether the day was good; giving up after one broken day|
|Habits|Practice|Every habit chosen by reason and built by practice; Epictetus taught that each act strengthens the habit it belongs to, so each refusal makes the next easier (Discourses II.18)|Habits formed by drift rather than choice; excusing them as just how you are|
|Alcohol in social settings|Avoid relying on it|Show up clear; if a drink feels necessary to be at ease with people, that ease is the thing to train|Drinking to get through a party, a family gathering, or awkwardness; teaching children that adults need it|
|Voluntary hardship and extreme challenges|Practice, with an examined motive|Marathons, fasts, cold, and sparring as training of the will, so hardship finds you ready; ask whether it makes you better toward others|Hard things for image or ego; becoming short-tempered or neglecting family in the name of training|
|Combat sports and martial training|In moderation|Training that teaches humility, discipline, and calm under pressure|Using the skill to intimidate; pride in being able to hurt people|$q$, 345, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Small habits$q$, 1020, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Small habits.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

None of these is a grave vice on its own. Each is a place where the body acts without your choosing, which makes them the best ground for training attention. The method is the same for all of them: never feed the habit once, and count the days, as Epictetus told the angry man to count the days he was not angry (Discourses II.18).

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Nail biting|Avoid|Catch the hand at the mouth and refuse it; keep nails short so there is nothing to bite, as you would keep wine out of the house|Letting boredom, worry, or hard thinking move your hands for you|
|Hitting snooze|Avoid|Rise at the first alarm; you were made to act, not to stay under the blankets (Meditations V.1)|Bargaining with the alarm; starting the day with a small defeat|
|Complaining|Avoid|Say nothing about what is not up to you; act on what is|Complaint as conversation; every complaint assents to the judgment that something outside your will is bad|
|Swearing and coarse talk|Avoid|Plain, clean speech; Epictetus advised against coarse talk and silence when others fall into it (Handbook 33)|Cursing from habit or anger; coarse speech makes coarse conduct easier|
|Interrupting|Avoid|Hear the whole answer before you speak; Socrates's method depended on it|Waiting for your turn instead of listening; finishing other people's sentences|
|Nicotine and vaping|Avoid|A body and mind that need nothing to feel steady|Dependence by design; it fails the master or slave test outright|
|Filler words and fidgeting|Practice correcting|Notice and cut them; harmless in themselves, they are good practice in attention|Treating them as too small to bother with|
|Posture|Practice|Stand and sit with attention, the body carried as something you govern|Slumping by default for hours at a desk or on a couch|$q$, 285, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Home, family, and difficult people$q$, 1021, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Home, family, and difficult people.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Raising your voice at your children|Avoid|Discipline by self-control, which children learn by watching it; the sage never assents to the angry impression, and on examination there is usually nothing to be angry about|Yelling as discipline, which teaches self-control by losing it; letting exhaustion speak for you|
|When a child breaks or loses something|Practice|Treat it as a lesson, not a catastrophe; Epictetus taught that if you love a jug, remember it is a jug, and you won't be upset when it breaks (Handbook 3)|Fury over an object; making a child feel less valuable than the thing lost|
|Helping family and friends|Practice|Serve willingly and keep no count; refuse only when helping would be unjust or would make the person worse, as Socrates refused the Thirty|Saying yes, then keeping a silent ledger of what you are owed|
|Extended family and visits|Practice|Patience and presence, treating the difficulty as training; Socrates said living with Xanthippe prepared him for anyone, as a horse trainer who masters a spirited horse can handle the rest (Diogenes Laertius II.37). The drain comes from your judgments about the visit, not the visitors; if something needs saying, say it plainly|Withdrawing into sullen silence; or losing yourself to everyone else's expectations|
|Complainers and draining people|Practice patience|Listen with compassion, remember that no one does wrong willingly, and do not absorb it|Joining the complaint; judging them; carrying it home|
|Expecting people to be better than they are|Avoid|Expect each morning to meet ungrateful, meddling people, as Marcus did, and treat them well anyway (Meditations II.1)|Shock and bitterness when friends and family fall short|
|Possessions, theft, and loss|Practice detachment|Hold things lightly; Epictetus pointed out that the angry victim of a theft values the same thing the thief does (Discourses I.18)|Anger over things taken or damaged; defining yourself by what you own|
|Wealth beyond need|Avoid|Enough, and then generosity|Piling up wealth far past need while others go without|$q$, 315, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > The inner life$q$, 1022, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > The inner life.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Self-examination|Practice|Examine your life daily; Socrates held the unexamined life not worth living (Apology 38a)|Drifting from day to day without asking how you are doing|
|Journaling|Practice|Write to see yourself clearly, as Marcus did in the Meditations|Writing only to vent, or to perform for an imagined reader|
|Prayer and worship|Practice|Piety according to your means, as Socrates sacrificed modestly and honored the gods (Memorabilia I.3.3)|Bargaining with God; religion for show|
|Meditation and reflection|Practice|Stillness that sharpens attention; Socrates stood thinking for hours|Using it to escape responsibility rather than face it|
|Adversity|Practice acceptance|Treat hardship as training, as Seneca taught (On Providence); follow willingly, as Cleanthes prayed|Self-pity; blaming others; asking why me|
|Death|Practice remembering|Keep mortality in view, not to despair but to live well now; Socrates would not claim to know death is evil (Apology 29a)|Pretending it will not come; letting fear of it run your life|$q$, 146, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true)
) as v(program_id, author, work, section_label, chunk_index, chunk_text, word_count, translator, source_url, edition_year, text_type, source_type, language, difficulty, verification_status, deprecated)
join public.corpus_synthesis_documents sd on sd.doc_key = $q$virtues-of-socrates$q$ and sd.version = 1
on conflict (author, work, program_id, chunk_index) do nothing;


commit;
