-- Loads The Virtues of Socrates in Plato and Xenophon, version 1 (66 chunks), part 3 of 3,
-- into the synthesis layer defined in 20260929133029_synthesis_layer_documents.sql.
-- See academy/corpus-ingestion/synthesis/README.md.
--
-- Generated by: node academy/corpus-ingestion/ingest-synthesis.js --emit-sql --file virtues-of-socrates.v1.md --part 3/3
-- from the committed Markdown; the body is its output, unedited. Rows are written
-- without embeddings. The corpus agent's nightly synthesis sync (or the same script
-- run with keys) embeds live chunks that lack one; until then no match_rag_corpus*
-- function can return them, since each requires embedding is not null.
--
-- Touches no existing row. Every insert is on conflict do nothing.

begin;
-- The Virtues of Socrates in Plato and Xenophon, version 1: 66 chunks; part 3 of 3, chunks 1045 to 1066
insert into public.corpus_synthesis_documents
  (doc_key, version, title, author, created_at, generated_with, reviewed_by, sources_used, regenerate_when, file_path, content_sha256)
values ($q$virtues-of-socrates$q$, 1, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Arete (AI-assisted)$q$, $q$2026-09-29$q$::date, $q$Claude, Claude Docs (claude.ai)$q$, null, array[$q$Plato | Apology$q$, $q$Plato | Gorgias$q$, $q$Xenophon | Memorabilia$q$, $q$Seneca | Letters$q$, $q$Seneca | On Providence$q$, $q$Seneca | On Anger$q$, $q$Seneca | On Leisure$q$, $q$Seneca | On Benefits$q$, $q$Seneca | On Peace of Mind$q$, $q$Seneca | On the Shortness of Life$q$, $q$Epictetus | Discourses$q$, $q$Epictetus | Enchiridion$q$, $q$Marcus Aurelius | Meditations$q$, $q$Musonius Rufus | Lectures$q$, $q$Diogenes Laërtius | Lives of Eminent Philosophers$q$]::text[], array[$q$Plato, Symposium$q$, $q$Plato, Crito$q$, $q$Plato, Phaedo$q$, $q$Plato, Laches$q$, $q$Xenophon, Apology$q$, $q$Xenophon, Symposium$q$]::text[], $q$academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, $q$0ea0193d5389c2a5a9ec7412b2c9f85c0ba089641ad80d64095b21d1b4962501$q$)
on conflict (doc_key, version) do nothing;
insert into public.rag_corpus (program_id, author, work, section_label, chunk_index, chunk_text, word_count, translator, source_url, edition_year, text_type, source_type, language, difficulty, verification_status, deprecated, synthesis_document_id)
select v.*, sd.id from (values
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Epictetus > The body and possessions$q$, 1045, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Epictetus > The body and possessions.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Give the body only what it needs. Food, drink, clothing, house, and household only as far as need requires; cut off everything for show or luxury (Handbook 33).

- Let the body be the measure. The body measures what you should own as the foot measures the shoe. Go past the measure and there is no stopping; the shoe becomes gilded, then purple, then jeweled (Handbook 39).

- Tend the body in passing. Spending much time on exercise, eating, drinking, and the body's other functions is a sign of a dull mind. Give your main strength to reason (Handbook 41).

- Be chaste, without judging others. Keep yourself pure before marriage, but do not be harsh with those who are not, and do not boast of your own conduct (Handbook 33).

- Train in secret. If you live frugally, do not boast of it. If you train yourself in hardship, do it for yourself and not for show: when you are very thirsty, rinse your mouth with water and tell no one (Handbook 47).

- Take the smaller share. At a shared meal, the largest portion suits the appetite but not the fellowship (Handbook 36).

- Bear illness as a test. Fever, thirst, and hunger are the time to show what your training was for. Bear them without blaming God or man (Discourses III.10).$q$, 218, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Epictetus > Training and progress$q$, 1046, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Epictetus > Training and progress.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Feed the habits you want and starve the rest. Every habit grows by the acts that match it. To end one, stop doing it and do something else in its place. Count the days you were not angry: every day, then every other day, then every third (Discourses II.18).

- Train hardest against your own weakness. If you lean toward pleasure, lean past the middle the other way for training. If you are irritable, practice being insulted without being vexed (Discourses III.12).

- Begin with small things. When a little oil is spilled or a little wine stolen, say, "This is the price of peace of mind" (Handbook 12).

- Be able to be alone. Be sufficient for yourself and your own companion, with thoughts to occupy you (Discourses III.13).

- Treat your rules as laws. Keep the rules you adopt as if breaking them would be sacrilege, and ignore what anyone says about it (Handbook 50).

- Stop postponing. You are no longer a boy. Now is the contest and it cannot be put off. You are not yet Socrates, but live as one who wants to be (Handbook 50).

- Practice first, proof second, logic last. The first thing is to not lie; the second, knowing why; the third, knowing why the proof holds. We do it backwards, and lie while proving that lying is wrong (Handbook 51).

- Know the signs of progress. The one making progress blames no one, praises no one, and accuses no one. He looks to himself for all help and harm, smiles at praise, makes no defense against criticism, and watches himself like an enemy lying in ambush (Handbook 48).$q$, 271, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Epictetus > To keep at hand$q$, 1047, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Epictetus > To keep at hand.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Epictetus told his students to have these ready on every occasion (Handbook 51):

- Cleanthes's prayer, "Lead me, Zeus, and you, Destiny," wherever you have set me; I will follow willingly, and if I would not, I would follow anyway.

- "If it pleases the gods, so be it" (Socrates to Crito).

- "Anytus and Meletus can kill me, but they cannot harm me" (Socrates at his trial).$q$, 65, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Seneca$q$, 1048, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Seneca.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Seneca wrote as a man still in training, writing to a friend in training. His rules come from the Letters to Lucilius (Gummere's translation, cited by letter number) and his essays (Stewart's translation): On Anger, On Benefits, On Providence, On Peace of Mind, and On the Shortness of Life.$q$, 49, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Seneca > Time and death$q$, 1049, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Seneca > Time and death.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Hold every hour in your grasp. Do today's work today and you will depend less on tomorrow. While we postpone, life speeds by. Time is the only thing that is truly ours, and we let anyone take it (Letters 1).

- Live each day as if it completed your life. Every day should be arranged as though it closed the series and rounded out your existence (Letters 12).

- Stop complaining that life is short. Life is long enough if you know how to use it. We are not given a short life; we waste a long one on greed, useless busyness, wine, sloth, and ambition (On the Shortness of Life 1 to 2).

- Fear the thought of death, not death. Death is always the same distance away. What we fear is our idea of it (Letters 30).$q$, 136, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Seneca > The body and wealth$q$, 1050, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Seneca > The body and wealth.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Treat the body strictly so it obeys the mind. Indulge it only as far as health requires. Eat to end hunger, drink to end thirst, dress to keep out the cold, and live in a house that keeps out the weather; thatch shelters as well as marble (Letters 8).

- But do not torture it for show. Living by nature does not mean being dirty on purpose, dressing in rags, or eating disgusting food to be admired. Seeking out dainties is luxury; avoiding ordinary, inexpensive things is madness (Letters 5).

- Measure wealth by desire, not by holdings. The poor man is not the one who has little but the one who craves more. The right limit is first what is necessary, then what is enough (Letters 2).

- Live by nature, not opinion. "If you live according to nature, you will never be poor; if according to opinion, you will never be rich." Nature needs little; opinion is never satisfied (Letters 16, quoting Epicurus).

- Rehearse poverty. Set aside days to live on the cheapest food and roughest clothes, and ask yourself, "Is this what I feared?" Toughen the soul while fortune is kind (Letters 18).

- Keep exercise short. Choose simple exercises that tire the body quickly and save your time for the mind (Letters 15).

- Never get drunk. Drunkenness is madness taken on purpose; stretch it over several days and no one would doubt the man was insane (Letters 83).$q$, 238, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Seneca > Fear and the mind$q$, 1051, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Seneca > Fear and the mind.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Do not suffer before the event. More things frighten us than crush us; we suffer more in imagination than in reality. Do not be unhappy before the crisis comes (Letters 13).

- Change your soul, not your scenery. Travel does not cure a troubled mind, because you take yourself along. As Socrates said, you travel with yourself (Letters 28).

- Find quiet inside the noise. You are at peace when no noise reaches you and no word, flattering or threatening, shakes you out of yourself. Still, when you can avoid the uproar, avoid it (Letters 56).

- Welcome hardship as training. God does not pet the good man; he tests him, hardens him, and fits him for himself. The veteran looks calmly at his own wounds; the recruit turns pale at the thought of one (On Providence 1, 4).

- Set your own limit on success. Nothing frees you from hope and fear like halting of your own accord, before fortune chooses to stop you (On Peace of Mind 10).$q$, 166, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Seneca > Anger and other people$q$, 1052, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Seneca > Anger and other people.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Delay is the greatest cure for anger. Ask anger for time, not to pardon the offense but to judge it rightly. If it waits, it ends (On Anger II.29).

- Ask whether you have done the same. Before condemning, ask whether you have ever committed that fault or made that mistake yourself (On Anger II.28 to 29).

- Review every day before you sleep. Ask what bad habit you cured today, what fault you resisted, and in what way you are better. Anger calms when it knows it must face a judge each night (On Anger III.36).

- Treat those below you as you would be treated by those above. Remember that someone has as much power over you as you have over those who serve you (Letters 47).

- Give and forget; receive and remember. The giver should forget at once that he gave; the receiver should never forget that he received. Never remind anyone of what you did for them (On Benefits II.10).

- Serve however you still can. If public life is closed to you, serve in private. If you cannot speak, help with silent counsel. Socrates kept encouraging Athens under the Thirty (On Peace of Mind 4 to 5).$q$, 198, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Seneca > Company, reading, and friendship$q$, 1053, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Seneca > Company, reading, and friendship.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Avoid the crowd. Seneca came home from the crowds and the games more greedy, more ambitious, more self-indulgent, and even more cruel. Nothing damages character so much as lounging at the shows (Letters 7).

- Judge a friend before, trust him after. Think long about whether to admit someone to your friendship. Once you have, trust him as you trust yourself (Letters 3).

- Choose a guardian and live under his eyes. Pick a Cato, or if Cato is too severe, a gentler Laelius, and picture him always as your protector and pattern. You cannot straighten what is crooked without a ruler (Letters 11).

- Read few authors, deeply. Linger with a limited number of master thinkers and digest them. Everywhere means nowhere; the one who travels constantly has many acquaintances and no friends (Letters 2).

- Be able to stay put. The first sign of a well-ordered mind is the ability to remain in one place and keep your own company (Letters 2).$q$, 160, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Seneca > Rest$q$, 1054, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Seneca > Rest.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Alternate solitude and company. Solitude cures us when we are sick of crowds, and crowds cure us when we are sick of solitude (On Peace of Mind 17).

- Let the mind relax. It should not always be strained to the same pitch. Socrates played with little boys, Cato refreshed his mind with wine after affairs of state, and Scipio danced. Seneca even allows wine now and then to wash away cares, adding that moderation is wholesome both in freedom and in wine (On Peace of Mind 17).$q$, 87, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Marcus Aurelius$q$, 1055, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Marcus Aurelius.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Marcus wrote his rules to himself, as an emperor trying to stay a good man. They come from the Meditations (Long's translation, cited by book and section).$q$, 27, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Marcus Aurelius > The morning and the day$q$, 1056, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Marcus Aurelius > The morning and the day.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Expect difficult people before you leave the house. Begin each morning by telling yourself you will meet the meddler, the ungrateful, the arrogant, the deceitful, the envious. They act from ignorance of good and evil, and they are your kin, so you cannot be harmed by them or angry with them (II.1).

- Get up. When you rise unwillingly, remember that you are rising to do the work of a human being. The plants, birds, ants, and bees all do their work. Were you made to lie under the blankets and keep warm (V.1)?

- Do each act as if it were your last. Put aside carelessness, pretense, self-love, and discontent with your lot (II.5).

- Cut the unnecessary. Most of what we say and do is unnecessary. On every occasion ask, "Is this one of the unnecessary things?" Cut unnecessary thoughts too, and unnecessary acts will not follow (IV.24).

- Do your duty whatever your condition. Let it make no difference whether you are cold or warm, tired or rested, criticized or praised, dying or doing something else (VI.2).$q$, 176, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Marcus Aurelius > Death and time$q$, 1057, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Marcus Aurelius > Death and time.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Be good now. Do not act as if you had ten thousand years. Death hangs over you. While you live and while you can, be good (IV.17).

- Take troubles one at a time. Do not think about all the troubles of your whole life at once. Ask of the present one, "What here is unbearable?" and you will be ashamed to answer. Only the present can hurt you, and it is small (VIII.36).$q$, 73, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Marcus Aurelius > Judgment and the mind$q$, 1058, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Marcus Aurelius > Judgment and the mind.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Blame your judgment, then change it. If something outside you causes pain, it is your judgment of it that disturbs you, and you can wipe that judgment out now. If something you are not doing troubles you, why not act instead of complaining (VIII.47)?

- Dye your mind with good thoughts. Your character becomes like your habitual thoughts, because the soul is dyed by them. Where a man can live, he can live well, even in a palace (V.16).

- Stand like a promontory. Be like the headland the waves keep breaking against, which stands firm and calms the water around it. Do not say "I am unlucky because this happened" but "I am lucky, because it happened and I remain unhurt" (IV.49).

- Retreat into yourself. You need no country house or seashore. Nowhere is quieter than your own soul, and you can go there whenever you choose (IV.3, VII.28).

- Look within. The spring of good is inside you, and it will keep flowing if you keep digging (VII.59).

- Stand upright on your own. Be cheerful and do not seek the calm that others give. A man must stand upright, not be held upright (III.5).$q$, 193, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Marcus Aurelius > Other people$q$, 1059, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Marcus Aurelius > Other people.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Be strict with yourself and forgiving of others. Marcus never puts it in one line, but it runs through the whole book. When someone wrongs you, ask what he took to be good; then you will pity him, and it is your duty to pardon him (VII.26). The gods put up with bad men for ages; are you tired of it already, when you are one of them (VII.70)? What is asked of you is tolerance toward others and self-restraint in yourself (V.33).

- Teach them or bear with them. People exist for one another (VIII.59). If someone is wrong, correct him kindly and show him his mistake. If you cannot, blame yourself, or blame no one (X.4).

- Do not demand that bad people not exist. When someone's shamelessness offends you, ask whether a world without shameless people is possible. It is not, so do not require the impossible (IX.42).

- Take revenge by not becoming like him. The best revenge is not to become like the one who wronged you (VI.6).

- Do good and move on. Do not call people over to see the good you have done. Go on to the next good act, as a vine bears grapes season after season (V.6).

- Do not wait for a perfect world. Do what nature asks now, without looking around to see who is watching. Do not expect Plato's Republic; be satisfied if the smallest thing goes well (IX.29).$q$, 237, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Marcus Aurelius > Character$q$, 1060, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Marcus Aurelius > Character.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Stop talking about the good man and be one. No more discussing what a good man should be. Be one (X.16).

- If it is not right, do not do it; if it is not true, do not say it (XII.17).

- Do not let power change you. Do not be "made into a Caesar" or dyed with that dye. Keep yourself simple, good, pure, serious, unaffected, just, reverent, kind, affectionate, and strenuous in doing what is right. Honor God and help people. Life is short (VI.30).

- Do not show off your discipline. From Rusticus, Marcus learned not to make a display of his self-discipline or his good deeds, and to avoid fine writing and speeches (I.7).$q$, 115, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Famous episodes from works not yet in the corpus$q$, 1061, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Famous episodes from works not yet in the corpus.
Verification: unverified: written from general knowledge and not checked against a corpus text.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

These come from Plato's Symposium, Laches, Crito, and Phaedo, and Xenophon's Apology. They are well known and widely cited, but they were written from general knowledge rather than checked against a corpus text, so verify them before quoting.$q$, 38, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$unverified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Famous episodes from works not yet in the corpus > Courage$q$, 1062, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Famous episodes from works not yet in the corpus > Courage.
Verification: unverified: written from general knowledge and not checked against a corpus text.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- He saved Alcibiades at Potidaea. Alcibiades says Socrates rescued him when he was wounded, and then insisted the prize for valor go to Alcibiades instead of himself (Symposium 220d to 220e).

- He kept his head in the retreat from Delium. While the army fled, Socrates walked calmly with Laches, looking so formidable that no one dared attack them (Symposium 221a to 221b; Laches 181b).

- He drank the hemlock calmly. He comforted his weeping friends, took the cup without trembling, and his last words asked Crito to pay a debt of a rooster to Asclepius (Phaedo 116b to 118a).$q$, 98, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$unverified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Famous episodes from works not yet in the corpus > Self-discipline$q$, 1063, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Famous episodes from works not yet in the corpus > Self-discipline.
Verification: unverified: written from general knowledge and not checked against a corpus text.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- He walked barefoot on the ice at Potidaea. In a bitter winter, when other soldiers wrapped their feet in felt, he went out in his ordinary cloak and marched barefoot (Symposium 220a to 220b).

- He could drink all night and never get drunk. At Agathon's banquet he outlasted everyone, then left at dawn to spend the day as usual (Symposium 220a, 223c to 223d).

- He resisted Alcibiades. The most desired young man in Athens tried to seduce him, and Socrates declined, valuing Alcibiades's soul over his beauty (Symposium 217a to 219d).$q$, 91, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$unverified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Famous episodes from works not yet in the corpus > Wisdom$q$, 1064, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Famous episodes from works not yet in the corpus > Wisdom.
Verification: unverified: written from general knowledge and not checked against a corpus text.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- He stood thinking from one dawn to the next. At Potidaea he stood lost in thought through a whole day and night, then prayed to the sun and walked away (Symposium 220c to 220d).$q$, 34, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$unverified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Famous episodes from works not yet in the corpus > Justice$q$, 1065, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Famous episodes from works not yet in the corpus > Justice.
Verification: unverified: written from general knowledge and not checked against a corpus text.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- He refused to escape from prison. When Crito arranged his escape, Socrates refused, arguing that one must never return wrong for wrong, and letting the Laws of Athens make their case to him (Crito 49a to 54d).

- He preferred an unjust death to a just one. When a friend lamented that he was being put to death unjustly, Socrates asked whether he would rather see him put to death justly (Xenophon, Apology 28).$q$, 73, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$unverified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Sources$q$, 1066, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Sources.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

From the Arete corpus: Plato, Apology and Gorgias, trans. Benjamin Jowett; Xenophon, Memorabilia, trans. H. G. Dakyns. The final section draws on Plato's Symposium, Laches, Crito, and Phaedo and Xenophon's Apology, none yet in the corpus.

The section on a Socratic life in modern terms also draws on Seneca's Letters, On Providence, and On Anger; Epictetus's Discourses and Handbook; Marcus Aurelius's Meditations; Cleanthes; and Musonius Rufus. The feats section adds Diogenes Laertius VI, Xenophon's Symposium, and Plutarch's Cato the Younger. Its verdicts on modern activities are applications of their principles, not their words.$q$, 93, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true)
) as v(program_id, author, work, section_label, chunk_index, chunk_text, word_count, translator, source_url, edition_year, text_type, source_type, language, difficulty, verification_status, deprecated)
join public.corpus_synthesis_documents sd on sd.doc_key = $q$virtues-of-socrates$q$ and sd.version = 1
on conflict (author, work, program_id, chunk_index) do nothing;

select public.activate_synthesis_version(id) from public.corpus_synthesis_documents where doc_key = $q$virtues-of-socrates$q$ and version = 1;

commit;
