-- Synthesis Agent — the fourth autonomous agent in the Arete AI Agent System.
-- Adds the review-workflow table for generated cross-source synthesis documents
-- and a generic per-agent config table the admin dashboard can tune at runtime.
--
-- NOTE on rag_corpus.text_type: it is a free-text column defaulting to 'primary'
-- with NO existing CHECK constraint, and the live corpus holds thousands of rows
-- with text_type='primary'. The original build spec proposed adding a CHECK that
-- EXCLUDED 'primary' — that would fail against every existing row — so it is
-- intentionally omitted. text_type='synthesis' is already a valid value, so the
-- synthesis ingestion needs no schema change to rag_corpus.

-- One row per synthesis document, before and after ingestion.
CREATE TABLE IF NOT EXISTS synthesis_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Identity
  title TEXT NOT NULL,
  synthesis_type TEXT NOT NULL
    CHECK (synthesis_type IN ('cross_thinker', 'concept_evolution', 'practical')),
  concept TEXT NOT NULL,

  -- Source tracking
  authors_covered TEXT[] NOT NULL DEFAULT '{}',
  works_covered TEXT[] NOT NULL DEFAULT '{}',
  source_chunk_ids UUID[] DEFAULT '{}',

  -- The document itself (~2000 words, generated by Claude Sonnet)
  content TEXT NOT NULL,
  word_count INT,

  -- Demand signal (why this was generated)
  user_theme_frequency INT DEFAULT 0,
  demand_rank INT,

  -- Review workflow
  status TEXT NOT NULL DEFAULT 'pending_review'
    CHECK (status IN ('pending_review', 'approved', 'rejected', 'ingested', 'edited')),
  reviewed_at TIMESTAMPTZ,
  review_notes TEXT,

  -- Ingestion tracking
  ingested_at TIMESTAMPTZ,
  rag_chunk_ids UUID[] DEFAULT '{}',

  -- Generation metadata
  generation_week DATE NOT NULL,           -- Monday (UTC) of the week generated
  generation_model TEXT DEFAULT 'claude-sonnet-4-6',
  prompt_tokens INT,
  completion_tokens INT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_synthesis_concept ON synthesis_documents(concept);
CREATE INDEX IF NOT EXISTS idx_synthesis_status ON synthesis_documents(status);
CREATE INDEX IF NOT EXISTS idx_synthesis_week ON synthesis_documents(generation_week DESC);
CREATE INDEX IF NOT EXISTS idx_synthesis_pending ON synthesis_documents(status) WHERE status = 'pending_review';

-- Generic agent configuration — lets the admin dashboard adjust agent parameters
-- (e.g. documents_per_week) without a redeployment.
CREATE TABLE IF NOT EXISTS agent_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_name TEXT NOT NULL UNIQUE,
  config JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO agent_config (agent_name, config)
VALUES (
  'synthesis_agent',
  '{
    "documents_per_week": 5,
    "min_user_frequency": 3,
    "target_word_count": 2000,
    "synthesis_types": ["cross_thinker", "concept_evolution", "practical"],
    "enabled": true
  }'
)
ON CONFLICT (agent_name) DO NOTHING;

-- RLS — no policies; service role only for writes. The admin web app reads via
-- the service-role admin client behind ADMIN_EMAIL-gated API routes.
ALTER TABLE synthesis_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_config ENABLE ROW LEVEL SECURITY;
