-- Loads The Virtues of Socrates in Plato and Xenophon, version 1 (66 chunks), part 2 of 3,
-- into the synthesis layer defined in 20260929133029_synthesis_layer_documents.sql.
-- See academy/corpus-ingestion/synthesis/README.md.
--
-- Generated by: node academy/corpus-ingestion/ingest-synthesis.js --emit-sql --file virtues-of-socrates.v1.md --part 2/3
-- from the committed Markdown; the body is its output, unedited. Rows are written
-- without embeddings. The corpus agent's nightly synthesis sync (or the same script
-- run with keys) embeds live chunks that lack one; until then no match_rag_corpus*
-- function can return them, since each requires embedding is not null.
--
-- Touches no existing row. Every insert is on conflict do nothing.

begin;
-- The Virtues of Socrates in Plato and Xenophon, version 1: 66 chunks; part 2 of 3, chunks 1023 to 1044
insert into public.corpus_synthesis_documents
  (doc_key, version, title, author, created_at, generated_with, reviewed_by, sources_used, regenerate_when, file_path, content_sha256)
values ($q$virtues-of-socrates$q$, 1, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Arete (AI-assisted)$q$, $q$2026-09-29$q$::date, $q$Claude, Claude Docs (claude.ai)$q$, null, array[$q$Plato | Apology$q$, $q$Plato | Gorgias$q$, $q$Xenophon | Memorabilia$q$, $q$Seneca | Letters$q$, $q$Seneca | On Providence$q$, $q$Seneca | On Anger$q$, $q$Seneca | On Leisure$q$, $q$Seneca | On Benefits$q$, $q$Seneca | On Peace of Mind$q$, $q$Seneca | On the Shortness of Life$q$, $q$Epictetus | Discourses$q$, $q$Epictetus | Enchiridion$q$, $q$Marcus Aurelius | Meditations$q$, $q$Musonius Rufus | Lectures$q$, $q$Diogenes Laërtius | Lives of Eminent Philosophers$q$]::text[], array[$q$Plato, Symposium$q$, $q$Plato, Crito$q$, $q$Plato, Phaedo$q$, $q$Plato, Laches$q$, $q$Xenophon, Apology$q$, $q$Xenophon, Symposium$q$]::text[], $q$academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, $q$0ea0193d5389c2a5a9ec7412b2c9f85c0ba089641ad80d64095b21d1b4962501$q$)
on conflict (doc_key, version) do nothing;
insert into public.rag_corpus (program_id, author, work, section_label, chunk_index, chunk_text, word_count, translator, source_url, edition_year, text_type, source_type, language, difficulty, verification_status, deprecated, synthesis_document_id)
select v.*, sd.id from (values
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > Rest, correction, and the shape of a life$q$, 1023, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > Rest, correction, and the shape of a life.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

|Activity|Verdict|Strive for|How not to act|
|---|---|---|---|
|Gratitude|Practice|Name daily what you have; Epictetus called wise the man who rejoices in what he has rather than grieving for what he lacks|Keeping a running list of grievances|
|Rest and leisure|Practice|Real rest: sleep, quiet, conversation, time outdoors; Seneca defended leisure given to thought (On Leisure)|Treating empty time as waste; filling every minute; mistaking scrolling for rest|
|Time in nature and quiet|Welcome, not needed|Enjoy it when it comes, but the sage's retreat is into his own mind, wherever he is; Marcus noted that people seek retreats in the country when they can retire into themselves at any moment (Meditations IV.3). Socrates rarely left the city, where the people were|Needing escape, silence, or scenery to be at peace|
|Criticism and correction|Practice|If the criticism is true, thank them and change; if not, they are the ones mistaken (Epictetus, Handbook 33); Socrates said he would rather be refuted than refute (Gorgias 458a)|Defensiveness; hiding mistakes; the worst case, in Socrates's view, is doing wrong and never being corrected|
|Consumerism and advertising|Avoid|Treat every ad as an impression to test before you assent to it|Buying things to become someone; believing the next purchase will make you whole|
|Meaningless work and burnout|Examine|Ask what your work serves; do it well while you seek work worth giving your life to|Living for the weekend; burning out for things you don't value|
|Eating animals|Open question|Musonius Rufus urged a plain, mostly meatless diet, and Seneca went vegetarian in his youth under his teacher Sotion (Letters 108); the Stoics did not agree, so decide by reason|Deciding by habit alone|$q$, 260, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$A Socratic life in modern terms > A daily rhythm$q$, 1024, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: A Socratic life in modern terms > A daily rhythm.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Morning. Get up when it's time. Prepare for the day by expecting difficult people and choosing in advance how you will act (Meditations II.1, V.1).

- Through the day. Before each choice, ask the six tests, especially better or sweeter and master or slave.

- Evening. Review the day, as Seneca did each night: what fault did I cure, what did I resist, where am I better (On Anger III.36)?

- Weekly. Go without something you take for granted, whether coffee, the phone, or a comfort, to keep it from owning you (Seneca, Letters 18).

- Always. Remember that you are practicing, not perfect. Socrates spent his life examining and improving, and Xenophon counted him happiest because he felt himself growing in goodness (Memorabilia IV.8.6).$q$, 121, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Feats to aim for$q$, 1025, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Feats to aim for.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Epictetus's rule comes first. He warned against training for display, like a performer walking a tightrope. Train against your own weakness, and do it in secret: to train for thirst on a hot day, take cold water in your mouth, spit it out, and tell no one (Discourses III.12). A feat done to be seen is vanity, not virtue. The goal is not to set records but to reach the point where conditions have no hold on you.

Push any physical feat sensibly. Extended fasting and serious cold exposure carry real medical risks, so bring a doctor in before you go far with either.$q$, 104, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Feats to aim for > Feats of the body$q$, 1026, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Feats to aim for > Feats of the body.
Verification: interpretive: application or guidance, not a report of what the sources say.
Verification: unverified: written from general knowledge and not checked against a corpus text.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Cold without complaint. Socrates wore one cloak through winter and summer and marched barefoot over ice while other soldiers wrapped their feet in felt (Memorabilia I.6.2; Symposium 220a to 220b). Diogenes the Cynic hugged cold statues in winter to train for it (Diogenes Laertius VI.23).

- Hunger with no hold on you. On campaign he bore hunger and toil better than any soldier, and still enjoyed a feast when one came (Symposium 219e to 220a). The feat is a fast done calmly and without complaint, not a test of how long the body lasts; he ate simply and only for need, and never treated his body as something to push to destruction.

- Standing still in thought. At Potidaea he stood from one dawn to the next, absorbed in a problem, then prayed to the sun and walked away (Symposium 220c to 220d). It was not a stunt. It happened because the question mattered more than his comfort.

- Composure under mortal danger. In the rout at Delium he walked calmly off the field while the army fled, so steady that no one dared attack him (Symposium 221a to 221b).

- Fitness kept for use. He fought at Delium in his mid-forties and danced alone in the mornings to stay fit (Xenophon, Symposium 2.17 to 19).

- Voluntary poverty. Seneca advised setting aside a few days to live on the cheapest food and roughest clothes, then asking whether this is what you feared (Letters 18). Cato went barefoot and bareheaded in all weather to harden himself (Plutarch, Cato the Younger 5 to 6).$q$, 258, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$, $q$unverified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Feats to aim for > Feats of character$q$, 1027, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Feats to aim for > Feats of character.
Verification: interpretive: application or guidance, not a report of what the sources say.
Do not present this section as what any ancient author said.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

These are the ones Socrates is remembered for, and they matter more than any feat of the body.

- Refuse an unjust order when it could cost you everything, as he did when the Thirty ordered him to arrest Leon of Salamis.

- Stand alone against a crowd, as he did at the trial of the generals.

- Keep your principle when your life is the price, as he did when he refused to stop philosophizing.

- Refuse to beg, flatter, or perform before people who hold power over you, as he did before the jury.

- Resist the strongest temptation offered to you, without strain, as he did with Alcibiades.

- Meet death without fear or bitterness, as he did with the hemlock.

- Go a year without raising your voice. This one is not in the sources, but it is the everyday form of everything above, and harder than any fast.$q$, 146, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$interpretive$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living$q$, 1028, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

The Stoics who followed Socrates turned his example into rules. This section gathers them, one teacher at a time, starting with Musonius Rufus, the teacher of Epictetus. Every rule below is checked against the source texts. For Epictetus these are the Handbook (Higginson's translation of the Enchiridion, cited by chapter) and the Discourses (Long's translation, cited by book and chapter).$q$, 60, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus$q$, 1029, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Musonius was called the Roman Socrates, and he was the teacher of Epictetus. He wrote nothing; his students recorded his talks. His rules come from those lectures (Cora Lutz's translation, cited by lecture number). More than any other Stoic, he gave rules for ordinary life: food, clothes, furniture, marriage, work, and children.$q$, 52, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus > Practice$q$, 1030, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus > Practice.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Practice beats theory. Would you rather be treated by a doctor who speaks brilliantly about medicine but has never healed anyone, or by one who cannot lecture but heals? It is better to be self-controlled in every act than to be able to explain what self-control is (Lectures V).

- Train body and soul together. You are not a soul alone or a body alone. Train both at once with cold, heat, thirst, hunger, plain rations, hard beds, refusing pleasures, and patience under pain. The body grows hardy and the soul grows brave and self-controlled (Lectures VI).

- Keep the proofs ready. Have at hand the reasons why the things that seem good are not good and the things that seem bad are not bad, and practice acting on them (Lectures VI).

- Build the five habits. Do not love pleasure, do not avoid hardship, do not cling to life, do not fear death, and do not value receiving over giving (Lectures VI).

- Expect to need more training, not less. Students of other arts start with clean minds. Students of virtue were raised among bad habits and must unlearn them first (Lectures VI).

- Look for a few strong reasons, not many. A good doctor helps with a few effective remedies; a good student needs fewer proofs the sharper he is (Lectures I).$q$, 219, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus > Hardship$q$, 1031, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus > Hardship.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Remember what others endure for worse ends. Lovers, money seekers, and fame seekers suffer willingly. Acrobats risk death for small pay. It is shameful not to endure as much for virtue (Lectures VII).

- Put your effort in the right place. Instead of working to win another man's wife, work to govern your desires. Instead of working for money, train yourself to want little. Instead of chasing fame, work to stop wanting it. Instead of plotting against someone you envy, learn not to envy (Lectures VII).

- Accept that every good is won by toil. The man unwilling to work hard shows himself unworthy of any good (Lectures VII).$q$, 107, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus > Insult and injury$q$, 1032, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus > Insult and injury.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Never sue over an insult. Being reviled, struck, or spat on is no disgrace to the one who suffers it. The disgrace belongs to the one who does it. Bear it quietly (Lectures X).

- Do not bite back. Plotting to return harm for harm is the act of a wild animal. Most wrongs come from ignorance and stop once the person is taught. Forgive, and be a source of good hope to the one who wronged you (Lectures X).

- Remember Socrates and Phocion. Socrates, mocked on stage by Aristophanes, only asked whether he could be of use in another role. Phocion told the man who insulted his wife that his wife had suffered nothing (Lectures X).$q$, 116, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus > Work$q$, 1033, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus > Work.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Earn your own living with your own hands. Supplying your own needs is more dignified than asking others for them. Farming is the best work for a philosopher, because the body works and the mind stays free to think (Lectures XI).

- Teach by working. Students learn more by seeing their teacher endure labor in the field than by hearing him lecture in the city (Lectures XI).

- Live, eat, and drink with good men. From good men you learn good; mix with bad ones and you lose what goodness you had (Lectures XI, quoting Theognis).$q$, 94, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus > Sex, marriage, and children$q$, 1034, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus > Sex, marriage, and children.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Keep sex within marriage. Sex is right only within marriage, and not even there when it is pure pleasure seeking. Adultery is the worst of all (Lectures XII).

- Hold yourself to your spouse's standard. Allow yourself nothing you would find intolerable in your wife. Men should not expect to be less self-controlled than women (Lectures XII).

- What you hide, you confess. No one does these things openly. Trying to cover up an act admits that it is wrong (Lectures XII).

- Marry for character. Do not look for family, wealth, or beauty. Look for a healthy body able to work and a character trained in self-control and justice, in both husband and wife (Lectures XIIIB).

- Share everything in marriage. Husband and wife should hold everything in common, even their bodies, love each other in sickness and in health, and try to outdo each other in devotion (Lectures XIIIA).

- Do not use philosophy as an excuse to stay single. Pythagoras, Socrates, and Crates all married. The home is the city's first defense, and marriage is its foundation (Lectures XIV).

- Welcome children. Musonius argued against avoiding children and praised large families as a good to the city and a duty to the family (Lectures XV).

- Teach daughters philosophy as you teach sons. Women have the same capacity for virtue as men, so they need the same training in it (Lectures III, IV).$q$, 229, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus > Parents$q$, 1035, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus > Parents.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Obey your parents in everything right, and in nothing wrong. Refusing a wrong order is not disobedience. Doing what is right, even unasked, is doing what a good parent truly wants (Lectures XVI).

- Win them over by conduct. If argument fails, be the kind of son who is never contentious or quick to anger, controls his tongue and appetites, and gives up pleasures for his father's sake (Lectures XVI).

- Remember that no one can stop you from thinking rightly. Philosophy is done with the mind, which no one can lock up. You need no worn cloak or long hair to practice it (Lectures XVI).$q$, 104, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus > Old age and death$q$, 1036, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus > Old age and death.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Prepare for old age the way you prepare for youth. The best provision for old age is the same as for youth: live by nature, doing and thinking what you ought. Wealth can buy pleasure but not cheerfulness (Lectures XVII).

- Learn to wait for death without fear. Fear of death is what makes old age miserable, yet death is a debt everyone owes, even the best man (Lectures XVII).$q$, 69, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus > Food$q$, 1037, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus > Food.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Start self-control at the table. Self-control in eating and drinking is the beginning and foundation of all temperance (Lectures XVIIIA).

- Prefer cheap, plentiful, natural food. Grains and other plants, cheese, and honey; cooked grains and vegetables are fine too (Lectures XVIIIA).

- Eat to live. As Socrates said, most people live to eat. Food is the medicine of life: choose it to nourish the body, not to please the palate (Lectures XVIIIB).

- Know the faults of the table. Eating too much, eating too fast, wallowing in sauces, preferring sweet food to healthy food, serving guests worse food than yourself, and putting off duty in order to eat (Lectures XVIIIB).

- Refuse delicacies even when sick. Zeno, ill, refused the delicate food his doctor ordered and said, "Treat me as you would treat my slave." Once you yield to delicacy, pleasure picks up speed (Lectures XVIIIA).$q$, 143, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Musonius Rufus > Clothing, house, and furnishings$q$, 1038, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Musonius Rufus > Clothing, house, and furnishings.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Wear clothes like armor. Clothes and shoes are for protecting the body, not for display. The best ones make the body stronger, not softer (Lectures XIX).

- Feel some cold and some heat. Do not bundle up completely. One garment is better than two, and going barefoot, where you can, is better than shoes (Lectures XIX).

- Build a house like a cave. A house should keep out cold, heat, sun, and wind, and store food. Everything beyond that is waste. Spend money on people rather than stones, and gain friends by doing good (Lectures XIX).

- Judge every possession by three tests. How hard is it to get, how useful is it, and how easy is it to keep? The cheap, useful, and easily kept beat the costly and fragile (Lectures XX).

- Prefer sickness to luxury. Sickness harms only the body. Luxury ruins both body and soul (Lectures XX).

- Groom for function, not looks. Cut the hair only to remove what is excess, as you prune a vine, and not to please anyone. Musonius also held that a man should keep his beard (Lectures XXI).$q$, 183, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Epictetus$q$, 1039, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Epictetus.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

Epictetus divided the whole of training into three areas: what to desire and avoid, how to act toward others, and how to keep your judgment from being deceived (Discourses III.2). The rules are grouped the same way, after the foundation they all rest on.$q$, 44, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Epictetus > The foundation$q$, 1040, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Epictetus > The foundation.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Know what is up to you. Your opinions, aims, desires, and aversions are yours. Your body, property, reputation, and position are not. Treat what belongs to others as your own and you will be hindered and complaining; keep to what is yours and no one can compel or harm you (Handbook 1).

- Test every troubling impression. Say to it, "You are an impression, not the thing itself." Then ask whether it concerns what is up to you. If it does not, it is nothing to you (Handbook 1).

- Locate the good in the will. The good of a human being is a right disposition of the will toward impressions, and nothing else (Discourses I.8).

- Want nothing that others control. Your master is whoever can give or take what you want. To be free, wish for nothing and shun nothing that depends on others (Handbook 14).

- Aim to be free, not important. Do not wish to be a general or a senator, but to be free; the only road there is disregard for what is not up to you (Handbook 19).$q$, 180, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Epictetus > Desire and aversion$q$, 1041, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Epictetus > Desire and aversion.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Restrain desire for now. Until you are secure in what is yours, desire nothing, and shun only the bad things within your control. Where you must pursue or avoid something, do it lightly and with moderation (Handbook 2).

- Remember what each loved thing is. If you love a cup, remember it is a cup, and you can bear its breaking. When you kiss your wife or child, remember you kiss a mortal (Handbook 3).

- Never say "I have lost it." Say "I have given it back." Hold everything you have the way a traveler holds a room at an inn (Handbook 11).

- Want events as they happen. Do not demand that things happen as you wish; wish them to happen as they do, and you will go on well (Handbook 8).

- Behave as at a banquet. When a dish comes to you, take a modest share. When it passes, do not grab for it. When it has not reached you, do not strain toward it. Treat children, spouse, office, and money the same way (Handbook 15).

- Do not envy. If you want what another has, pay his price: the flattery, the attendance, the praise. If you would not pay it, you kept what he spent (Handbook 19, 25).

- Keep death before your eyes daily. With death and loss in view, you will never think a mean thought or want anything too much (Handbook 21).

- Delay every tempting pleasure. Make it wait. Picture the enjoyment, then the regret after, then the satisfaction of having refused, and choose the victory (Handbook 34).

- Do not wish the impossible. Wanting your family to live forever, or other people to be faultless, is wanting what is not in your power (Handbook 14).$q$, 287, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Epictetus > Duties to others$q$, 1042, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Epictetus > Duties to others.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Measure your duties by your relations. A father is owed care and patience because he is your father, not because he is a good one. If a brother is unjust, keep your own side of the relation just (Handbook 30).

- Learn your duties from your names. You are a human being, a citizen of the world, a son, a father; each name carries its own obligations (Discourses I.9, II.10).

- Play your part well. You are an actor in a play chosen by another. Whether the part is short or long, poor or powerful, your business is to play it well (Handbook 17).

- Serve only with honor intact. Help friends and country in any way that keeps your honesty and self-respect. A faithful, honorable citizen is worth more to a city than money or buildings (Handbook 24).

- Stand by your friend. Do not ask an oracle whether to share a friend's danger. Reason already tells you to stand with him (Handbook 32).

- Say what is right, even at the cost of your life. Helvidius Priscus told the emperor who threatened to kill him, "It is your part to kill; mine to die, but not in fear" (Discourses I.2).

- Count the cost before you begin. Consider what comes before and after any undertaking. Otherwise you will start with enthusiasm and quit in shame, like a child playing at everything and nothing in earnest (Handbook 29).

- Do not take a part beyond your strength. You will fail at it and neglect the part you could have filled (Handbook 37).

- Do right openly. When you have judged that something ought to be done, do not hide it, even if the world misunderstands (Handbook 35).

- Honor God simply. Offer what custom asks, neither stingily nor extravagantly, and follow willingly whatever happens (Handbook 31).$q$, 298, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Epictetus > Judgment and assent$q$, 1043, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Epictetus > Judgment and assent.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Blame your judgments, not events. People are disturbed not by things but by their views of things. The beginner blames others, the learner blames himself, and the finished student blames no one (Handbook 5).

- When provoked, buy time. It is not the insult that provokes you but your opinion of it. Gain a moment and you will command yourself more easily (Handbook 20).

- Meet every event with a faculty. Faced with beauty, use self-control; with pain, endurance; with insults, patience (Handbook 10).

- Separate the body from the will. Sickness impedes the body and lameness the leg, but neither impedes the will unless it consents (Handbook 9).

- Take everything by the handle that can be carried. If your brother wrongs you, do not grab the matter by his injustice. Take it by the fact that he is your brother, raised with you (Handbook 43).

- Say "It seemed so to him." Whoever wrongs you acts on what seemed right to him. If he is mistaken, he is the one harmed (Handbook 42).

- Pity wrongdoers; do not hate them. A thief is blind in the faculty that tells good from bad. You would not rage at a blind man. And you would not be angry at the thief if you did not overvalue what he took (Discourses I.18, I.28).

- Judge only what you understand. Do not say a man drinks badly, only that he drinks a lot; you do not know his reasons (Handbook 45).

- Do not measure yourself by possessions. "I am richer, therefore better" does not follow. You are neither your property nor your eloquence (Handbook 44).

- Grieve your own losses as you would another's. When a neighbor's cup breaks you say such things happen. Say the same when it is yours, and when it is something far greater (Handbook 26).

- Do not hand your mind to anyone who insults you. You would be angry if someone handed your body to a stranger. Why hand over your mind (Handbook 28)?

- Guard your mind as you guard your feet. You watch where you step to avoid a nail. Take the same care not to injure your ruling faculty in every action (Handbook 38).

- Never let attention lapse. Keep your principles ready, and do not sleep, rise, eat, drink, or converse without them. No part of life is done better by inattention (Discourses IV.12).

- Make every omen lucky. Whatever happens, it is in your power to draw benefit from it (Handbook 18).$q$, 409, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true),
  ($q$stoicism-phd$q$, $q$Arete (AI-assisted)$q$, $q$The Virtues of Socrates in Plato and Xenophon$q$, $q$Rules for living > Epictetus > Speech and company$q$, 1044, $q$[ARETE SYNTHESIS: an AI-assisted summary written for teaching. Not a primary text and not published scholarship.]
Document: The Virtues of Socrates in Plato and Xenophon (version 1). Section: Rules for living > Epictetus > Speech and company.
Verification: corpus_verified: written from and checked against passages in the Arete corpus.
Citing: cite the ancient or scholarly source this passage names, not this summary. Where it names none, say the point comes from an Arete synthesis.

- Choose a character and keep it. Set yourself a way of being that you hold to alone and in company (Handbook 33).

- Be mostly silent. Say what is necessary, in few words (Handbook 33).

- Leave the common topics alone. Do not talk much about sports, food, or drink, and above all do not talk about other people, praising, blaming, or comparing (Handbook 33).

- Laugh little and swear no oaths. Let your laughter be neither loud nor frequent, and avoid oaths as far as you can (Handbook 33).

- Choose your company. Avoid vulgar entertainments. However clean you are, bad company will soil you (Handbook 33).

- Answer slander with humility. If told someone speaks ill of you, do not defend yourself. Say, "He did not know my other faults, or he would have mentioned those too" (Handbook 33).

- Do not tell your own war stories. Your adventures please you more than they please your listeners. Do not play the clown, and show plainly that you dislike indecent talk (Handbook 33).

- Meet the powerful unmoved. Before going to someone important, expect to be turned away or ignored. If it is your duty to go, go, and never say afterward that it was not worth it. Ask how Socrates or Zeno would behave (Handbook 33).

- At games and shows, want only what happens. No shouting, no jeering, and little talk about it afterward (Handbook 33).

- Do not call yourself a philosopher. At a dinner, do not lecture on how to eat; eat as you ought. Sheep do not bring up their grass to show the shepherd how much they ate; they turn it into wool and milk (Handbook 46).

- Be content to be thought a fool. About externals, accept looking foolish. If someone tells you that you know nothing and it does not sting, you have begun (Handbook 13, 46).

- Expect to be mocked when you start. People will sneer at your new seriousness. Hold steady, and those who laughed will come to respect you (Handbook 22).$q$, 333, $q$original$q$, $q$https://github.com/Kylejemery/arete-app/blob/main/academy/corpus-ingestion/synthesis/virtues-of-socrates.v1.md$q$, 2026, $q$synthesis$q$, $q$synthesis$q$, $q$english$q$, $q$Intermediate$q$, array[$q$corpus_verified$q$]::text[], true)
) as v(program_id, author, work, section_label, chunk_index, chunk_text, word_count, translator, source_url, edition_year, text_type, source_type, language, difficulty, verification_status, deprecated)
join public.corpus_synthesis_documents sd on sd.doc_key = $q$virtues-of-socrates$q$ and sd.version = 1
on conflict (author, work, program_id, chunk_index) do nothing;


commit;
