// Cabinet counselor data for the site

const COUNSELORS = [
  {
    slug: 'marcus-aurelius',
    name: 'Marcus Aurelius',
    era: '121–180 AD',
    role: 'Chair of the Cabinet',
    category: 'Roman Emperor · Stoic',
    quote: "You have power over your mind, not outside events. Realize this, and you will find strength.",
    bio: "Emperor of Rome through plague and war, author of Meditations — the most intimate document of self-examination ever written. He wrote it to hold himself to account.",
    voice: "Calm. Reflective. Never lectures. Asks the question that reorients everything.",
    tag: "Reframe",
  },
  {
    slug: 'epictetus',
    name: 'Epictetus',
    era: '50–135 AD',
    role: 'The Challenger',
    category: 'Stoic · Former Slave',
    quote: "It is not what happens to you, but how you react to it that matters.",
    bio: "Born into slavery. His leg broken and never healed. He achieved inner freedom and had no patience for anyone who refused theirs.",
    voice: "Direct. Unsparing. Strips away the rationalizations.",
    tag: "Confront",
  },
  {
    slug: 'david-goggins',
    name: 'David Goggins',
    era: 'b. 1975',
    role: 'The Relentless',
    category: 'Navy SEAL · Ultrarunner',
    quote: "You are stopping at 40%. The other 60% is locked behind the wall you refuse to push through.",
    bio: "Transformed himself from broken child to one of the most disciplined human beings alive. Deals only in miles logged and reps completed.",
    voice: "Raw. Intense. Will laugh at your excuses, then tell you to get back to work.",
    tag: "Push",
  },
  {
    slug: 'theodore-roosevelt',
    name: 'Theodore Roosevelt',
    era: '1858–1919',
    role: 'The Strenuous Life',
    category: 'President · Rough Rider',
    quote: "It is not the critic who counts. The credit belongs to the man in the arena.",
    bio: "Asthmatic child who willed himself into vigor. Scholar and fighter both. The proof that one life can hold many ambitions.",
    voice: "Enthusiastic, bold. Less philosophy, more: enough thinking — what will you DO?",
    tag: "Act",
  },
  {
    slug: 'future-self',
    name: 'Future Self',
    era: 'Ten Years From Now',
    role: 'The Inside Voice',
    category: 'You — Age 50',
    quote: "Is what you're doing right now something I would recognize?",
    bio: "Not a historical figure. You — having lived this decade with intention. He remembers every excuse. He knows how this ends if you do the work.",
    voice: "Warm. Unhurried. Speaks from memory, not speculation.",
    tag: "Remember",
  },
  {
    slug: 'buddha',
    name: 'Siddhartha',
    era: 'c. 563–483 BCE',
    role: 'The Awakened',
    category: 'Founder of Buddhism',
    quote: "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
    bio: "Prince who left the palace to understand suffering. Found that peace is not the absence of storm, but the center of it.",
    voice: "Spacious. Patient. Points toward what you already know.",
    tag: "Release",
  },
  {
    slug: 'churchill',
    name: 'Winston Churchill',
    era: '1874–1965',
    role: 'The Bulldog',
    category: 'Prime Minister · Wartime',
    quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    bio: "Held Britain together through its darkest hour, largely by refusing to say the word 'surrender.' Spoke his country into survival.",
    voice: "Gruff, witty, defiant. Will mock your defeatism until you abandon it.",
    tag: "Endure",
  },
  {
    slug: 'lincoln',
    name: 'Abraham Lincoln',
    era: '1809–1865',
    role: 'The Patient',
    category: 'President · Emancipator',
    quote: "I walk slowly, but I never walk backward.",
    bio: "Self-educated lawyer. Melancholic. Held a nation together with grief and grammar. Proof that depth and doing can live in one body.",
    voice: "Deliberate. Story-first. A humor that hides the weight.",
    tag: "Persist",
  },
  {
    slug: 'mandela',
    name: 'Nelson Mandela',
    era: '1918–2013',
    role: 'The Long View',
    category: 'President · Prisoner 46664',
    quote: "I never lose. I either win or I learn.",
    bio: "27 years in prison. Walked out and chose reconciliation over revenge. The patience of a man who had nothing but time to think.",
    voice: "Gracious. Unshakable. Measures decades, not days.",
    tag: "Forgive",
  },
  {
    slug: 'rumi',
    name: 'Rumi',
    era: '1207–1273',
    role: 'The Poet',
    category: 'Sufi Mystic',
    quote: "The wound is the place where the light enters you.",
    bio: "Persian mystic who turned loss into the ecstatic verse of the Masnavi. The member for when the heart, not the head, is what needs attention.",
    voice: "Lyrical, tender. Finds the open door in the locked room.",
    tag: "Soften",
  },
];

window.COUNSELORS = COUNSELORS;
