import Stoic.Themata.Generated

/-!
# The candidate log

Prints `results/candidates.md`, the record of every Phase 3 candidate and how
it was produced. Not imported by `Stoic.lean`; run it with

    lake env lean Stoic/Themata/Log.lean > ../results/candidates.md

and commit the result whenever a candidate changes.
-/

namespace Stoic.Themata

def shapesOf (c : Candidate) : List String := c.rules.map (·.shape)

def sameAs (c : Candidate) : String :=
  let others := candidates.filter fun d => d.name != c.name && shapesOf d == shapesOf c
  ", ".intercalate (others.map (·.name))

def row (i : Nat) (c : Candidate) : String :=
  let rules := if c.rules.isEmpty then "(none: base cases only)" else "<br>".intercalate (c.rules.map (·.name))
  s!"| {i + 1} | {c.name} | {c.provenance.label} | {rules} | {sameAs c} |"

def log : String :=
  let named := [attested, mates, matesDT]
  "\n".intercalate <|
    [ "# Phase 3 candidates"
    , ""
    , "Generated by `themata/lean/Stoic/Themata/Log.lean`; do not edit by hand."
    , "Rule shapes are defined in `Stoic/Themata/Rules.lean`, the generating"
    , "switches in `Stoic/Themata/Generated.lean`."
    , ""
    , s!"{candidates.length} candidates: {named.length} named, {generated.length} generated."
    , ""
    , "## Named candidates and their sources"
    , "" ] ++
    named.map (fun c => s!"- **{c.name}** ({c.provenance.label}): {c.source}") ++
    [ ""
    , "## All candidates"
    , ""
    , "| # | Candidate | Provenance | Rules | Same rule set as |"
    , "| --- | --- | --- | --- | --- |" ] ++
    (candidates.zipIdx.map fun (c, i) => row i c)

#eval IO.println log

end Stoic.Themata
